### PR TITLE
Disc 579 update xslt preservica6

### PR DESCRIPTION
**Pull request by VictorHarbo**
XSLT PR: 

Updates the XSLT to be able to handle records from both preservica 5 and 6. This is done by  using a lot more variables. 

NB: When this PR gets merged and solr gets updated there will be a lot of records with no streamingUrl, as records from pvica 6 doesnt contain this information yet. We should keep this in mind for demos.

### CODE REVIEW

**Review by tokee — CHANGES_REQUESTED** [review]
When running this on KB Preservica 6 test data, there is an error from transformation for 3 records. Unfortunately the error handler does not set `origin`, which is a required field, so Solr does not accept the output.

```Javascript
"add": { "doc" : {"resource_description":"VideoObject","id":"ds.tv:oai:io:d4ea826f-03d2-4379-9b75-1e84648bf7df","conditions_of_access":"TODO: placeholderCondition","internal_transformation_error":"true","internal_transformation_error_description":"err:XPTY0004: A sequence of more than one item is not allowed as the first argument of fn:substring-after() (\"hdl:109.1.4\/d4ea826f-03d2-4379-9b75...\", \"hdl:109.1.4\/d4ea826f-03d2-4379-9b75...\") "} },
"add": { "doc" : {"resource_description":"VideoObject","id":"ds.tv:oai:io:9634e1a1-cb3c-42f5-a8cb-9bd62786e1ce","conditions_of_access":"TODO: placeholderCondition","internal_transformation_error":"true","internal_transformation_error_description":"err:XPTY0004: A sequence of more than one item is not allowed as the first argument of fn:substring-after() (\"hdl:109.1.4\/9634e1a1-cb3c-42f5-a8cb...\", \"hdl:109.1.4\/9634e1a1-cb3c-42f5-a8cb...\") "} },
"add": { "doc" : {"resource_description":"VideoObject","id":"ds.tv:oai:io:8251144f-d50b-48f4-b862-8cfc7b23dc38","conditions_of_access":"TODO: placeholderCondition","internal_transformation_error":"true","internal_transformation_error_description":"err:XPTY0004: A sequence of more than one item is not allowed as the first argument of fn:substring-after() (\"hdl:109.1.4\/8251144f-d50b-48f4-b862...\", \"hdl:109.1.4\/8251144f-d50b-48f4-b862...\") "} },
```

**Comment by VictorHarbo** [comment]
> When running this on KB Preservica 6 test data, there is an error from transformation for 3 records. Unfortunately the error handler does not set `origin`, which is a required field, so Solr does not accept the output.
> 
> ```js
> "add": { "doc" : {"resource_description":"VideoObject","id":"ds.tv:oai:io:d4ea826f-03d2-4379-9b75-1e84648bf7df","conditions_of_access":"TODO: placeholderCondition","internal_transformation_error":"true","internal_transformation_error_description":"err:XPTY0004: A sequence of more than one item is not allowed as the first argument of fn:substring-after() (\"hdl:109.1.4\/d4ea826f-03d2-4379-9b75...\", \"hdl:109.1.4\/d4ea826f-03d2-4379-9b75...\") "} },
> "add": { "doc" : {"resource_description":"VideoObject","id":"ds.tv:oai:io:9634e1a1-cb3c-42f5-a8cb-9bd62786e1ce","conditions_of_access":"TODO: placeholderCondition","internal_transformation_error":"true","internal_transformation_error_description":"err:XPTY0004: A sequence of more than one item is not allowed as the first argument of fn:substring-after() (\"hdl:109.1.4\/9634e1a1-cb3c-42f5-a8cb...\", \"hdl:109.1.4\/9634e1a1-cb3c-42f5-a8cb...\") "} },
> "add": { "doc" : {"resource_description":"VideoObject","id":"ds.tv:oai:io:8251144f-d50b-48f4-b862-8cfc7b23dc38","conditions_of_access":"TODO: placeholderCondition","internal_transformation_error":"true","internal_transformation_error_description":"err:XPTY0004: A sequence of more than one item is not allowed as the first argument of fn:substring-after() (\"hdl:109.1.4\/8251144f-d50b-48f4-b862...\", \"hdl:109.1.4\/8251144f-d50b-48f4-b862...\") "} },
> ```

Oh that error is boring! I might have forgotten to include origin somewhere. Should be an easier fix, when I've located the specific part of the XSLT

**Comment by VictorHarbo** [comment]
I will fix the error handling in this PR and then I'll create a new internal JIRA for the actual error, which seems like a new one! Apparently these files contains multiple PID handles, which looks criminally alot alike

**Review by tokee — APPROVED** [review]
Looks good! Unit test runs and I completed both `ds.tv` and `ds.radio`-updates througn `ds-datahandler` after deploying on the devel machine.

**Pull request merged**
